export const ActionTypes = {
    GET_SCHOOLS :"GET_SCHOOLS",
    INDUIVAL_SCHOOLS : "INDUIVAL_SCHOOLS",
    LOGIN : "LOGIN",
    UPDATE_SCHOOL:"UPDATE_SCHOOL",
    DELETE_SCHOOL:"DELETE_SCHOOL",
    ADD_SCHOOL:"ADD_SCHOOL"
}